version: '3.1'
services:
  jupyter-pyspark:
    image:
        jupyter/pyspark-notebook 
    volumes: 
        - ./data:/home/jovyan/
    ports:
        - 8888:8888
    environment:
        DOCKER_STACKS_JUPYTER_CMD : nbclassic